kind: DatadogAgent
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
spec:
  global:
    site: "us5.datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    clusterName: vps-okd
  features:
    apm:
      enabled: true
      instrumentation:
        enabled: true
        targets:
          - name: "default-target"
            ddTraceVersions:
              python: "4"
            # ddTraceConfigs:
            #   - name: "DD_PROFILING_ENABLED"
            #     value: "auto"
    logCollection:
      enabled: true
      containerCollectAll: true
    usm:
      enabled: true
    npm:
      enabled: true
    liveProcessCollection:
      enabled: true
