apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: justneverlift
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/jfmatth/justneverlift.com
  ref:
    branch: master
