apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: justneverlift
  namespace: flux-system
spec:
  interval: 1m0s
  chart: ./_helm
  reconcileStrategy: Revision
  sourceRef:
    kind: GitRepository
    name: justneverlift