apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: justneverlift
  namespace: justneverlift
spec:
  interval: 10m
  chart:
    spec:
      chart: ./_helm
      version: '1.0.x'
      sourceRef:
        kind: GitRepository
        name: justneverlift
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2