apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: justneverlift
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: justneverlift

  filterTags:
    # Match vYYYY.MM.DD
    pattern: ^v(?P<YEAR>\d+)\.(?P<MONTH>\d+)\.(?P<DAY>\d+)$
    # Convert to semver: YEAR.MONTH.DAY
    # Example: v2026.01.03 → 2026.01.03
    extract: $YEAR.$MONTH.$DAY

  policy:
    semver:
      range: ">=0.0.0"

  digestReflectionPolicy: Always
  interval: 60m