apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: justneverlift
  namespace: flux-system
spec:
  interval: 60m
  chart: ./_helm
  sourceRef:
    kind: GitRepository
    name: justneverlift